### ISSUE TITLE
Accounts module

### ISSUE THREAD

**Issue by rossoskull** [cerebro-iiitv/cerebro-backend-2020#2]
* Create model for Accounts ( use AbstractBaseUser model )
* Create routes for
  - Registration
  - Obtaining token
  - Verification, so that we can send links in email and accounts can be verified through that.

**Comment by theyashshahs** [comment]
fields for the model?

**Comment by rossoskull** [comment]
@yashshah2820 now let's work on the routes

**Comment by theyashshahs** [comment]
sure sir

**Comment by theyashshahs** [comment]
routes for registration have been created APIs for the user have been created.

**Comment by yashshah2820** [comment]
@chauhanprakhar @Atishay990 complete obtaining token part

**Comment by theyashshahs** [comment]
This task has been completed.

**Comment by theyashshahs** [comment]
all the work for this issue has been done.

**Comment by thepushkarp** [comment]
This issue has been resolved via #5 and #13
